spring :
  kafka:
    kafka-server: localhost:9092 # 9092는 kafka서버의 포트번호이다.
    consumer:
      #       groupid는 컨슈머 그룹을 식별하는 ID로서, 동일한 그룹ID를 가진 컨슈머들은 메시지를 분담해서 consume한다.
      #       만약 여러 컨슈머가 다른 group-id를 가지고 한 topic을 listen하면 각기 메시지를 수신하여 메시지 전파 효과 발생
      group-id: product-group
      #       카프카내에 들어와있는 메시지 중에 처음들어와 있는 메시지부터 읽기 시작.
      #       (latest라는 것도 있는데 얘는 현 시점 이후에 들어오는 메시지만 읽는다.)
      auto-offset-reset: earliest